name: Pelican site CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: recursive
    - uses: alissapajer/gh-pages-pelican-action@0.1.10

      env:
        PELICAN_CONTENT_FOLDER: posts
        PELICAN_THEME_FOLDER: theme/basic
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
